const Images = {
    tab_home_selected: require('./5/alipay_21.png'),
    tab_home: require('./5/tab_0_normal.png'),
    tab_tax_selected: require('./5/tab_1_sel.png'),
    tab_tax: require('./5/tab_1_normal.png'),
    tab_service_selected: require('./5/tab_2_sel.png'),
    tab_service: require('./5/tab_2_normal.png'),
    tab_msg_selected: require('./5/tab_3_sel.png'),
    tab_msg: require('./5/tab_3_normal.png'),
    tab_mine_selected: require('./5/tab_4_sel.png'),
    tab_mine: require('./5/tab_4_normal.png'),
    // tab_mine_p4_avatar_2: require('./p4_avatar_2.png'),
    // tab_mine_p4_avatar_3: require('./p4_avatar_3.png'),
    tab_home_header: require('./1/tab_home_header.jpg'),
    tab_home_image_0: require('./1/tab_home_1.jpg'),
    tab_home_image_1: require('./1/tab_home_2.jpg'),
    tab_home_image_2: require('./1/tab_home_3.jpg'),
    tab_home_image_3: require('./1/tab_home_4.jpg'),
    tab_home_image_4: require('./1/tab_home_5.jpg'),

    tab_licai_header: require('./2/licai_header.jpg'),
    tab_licai_image_0: require('./2/licai_0.jpg'),
    tab_licai_image_1: require('./2/licai_1.jpg'),
    tab_licai_image_2: require('./2/licai_2.jpg'),
    tab_licai_image_3: require('./2/licai_3.jpg'),
    tab_licai_image_4: require('./2/licai_4.jpg'),
    tab_licai_image_5: require('./2/licai_5.jpg'),
    tab_licai_image_6: require('./2/licai_6.jpg'),

    tab_mine_new_header: require('./2/tab_mine_new_header.jpg'),
    tab_mine_new_0: require('./2/tab_mine_new_0.jpg'),
    tab_mine_new_1: require('./2/tab_mine_new_1.jpg'),
    alipay_29: require('./5/alipay_29.png'),
    icon_30: require('./2/icon_30.jpg'),
    icon_30_1: require('./2/icon_30_1.jpeg'),
    icon_31: require('./2/icon_31.jpg'),
    icon_32: require('./2/icon_32.jpg'),
    icon_33: require('./2/icon_33.jpg'),
    icon_34: require('./2/icon_34.jpg'),
    headImage: require('./headImage.jpeg'),

    tab_mine_header: require('./2/tab_mine_0.jpg'),
    tab_mine_image_1: require('./2/tab_mine_2.jpg'),
    tab_mine_image_2: require('./2/tab_mine_3.jpg'),
    tab_mouth_header: require('./3/tab_mouth_0.jpg'),
    tab_mouth_image_1: require('./3/tab_mouth_1.jpg'),
    tab_mouth_image_2: require('./3/tab_mouth_2.jpg'),
    tab_mouth_image_3: require('./3/tab_mouth_3.jpg'),
    tab_msg_header: require('./4/tab_msg_0.jpg'),
    tab_msg_image_1: require('./4/tab_msg_1.jpg'),
    tab_msg_image_2: require('./4/tab_msg_2.jpg'),
    civic_centre_header: require('./1/gjj_first_00.jpg'),
    civic_centre_image_1: require('./1/gjj_first_0.jpg'),
    civic_centre_image_2: require('./1/gjj_first_1.jpg'),
    civic_centre_image_3: require('./1/gjj_first_2.jpg'),
    civic_centre_image_4: require('./1/gjj_first_3.jpg'),
    accumulation_header: require('./1/gjj_scond_00.jpg'),
    accumulation_image_1: require('./1/gjj_scond_0.jpg'),
    accumulation_image_2: require('./1/gjj_scond_1.jpg'),
    accumulation_server_image: require('./1/gjj_thire.jpg'),
    accumulation_info_header: require('./1/gjj_four_header.jpg'),
    alipay_15: require('./5/alipay_15.png'),
    alipay_115: require('./5/alipay_115.jpg'),
    alipay_22: require('./5/alipay_22.png'),
    alipay_23: require('./5/alipay_23.png'),
    alipay_23_1: require('./5/alipay_23_1.png'),
    alipay_14: require('./5/alipay_14.png'),
    gjj_four_4: require('./1/gjj_four_4.jpg'),
    alipay_25: require('./5/alipay_25.png'),
    alipay_26: require('./5/alipay_26.png'),
    icon_1: require('./1/icon_1.jpg'),
    icon_2: require('./1/icon_2.jpg'),
    icon_12: require('./1/icon_12.jpg'),
    icon_112: require('./1/icon_112.jpg'),
    icon_6: require('./1/icon_6.jpg'),
    icon_4: require('./1/icon_4.jpg'),
    icon_5: require('./1/icon_5.jpg'),
    icon_15: require('./1/icon_15.jpg'),
    icon_17: require('./1/icon_17.jpg'),
    icon_100: require('./1/icon_100.jpg'),
    // tab_mine_p4_bg: require('./p4_bg.png'),
    gjj_thire_0: require('./1/gjj_thire_0.jpg'),
    gjj_thire: require('./1/gjj_thire.jpg'),
    icon_7: require('./1/icon_7.jpg'),
    alipay_28: require('./5/alipay_28.png'),
};
export default Images;